services:
  app:
    image: russell-marina-api:development
    build:
      target: development
    command: npm run dev
    environment:
      NODE_ENV: development
    ports:
      - 127.0.0.1:${APP_PORT}:3000
    volumes:
      - ./src:/app/src
      - ./views:/app/views
      - ./public:/app/public
      - ./data:/app/data
